package app

import "time"

const (
	MaxClippingSourceBytes      int64 = 20 << 30
	MaxClippingSourceDurationMS int64 = 4 * 60 * 60 * 1000
	MaxClippingStorageBytes     int64 = 100 << 30
	MaxClippingImportAttempts         = 5
	MaxClippingBatchJobs              = 100
	ClippingStageAnalysis             = "analysis"
)

type ClippingSourceKind string

const (
	ClippingSourceUpload      ClippingSourceKind = "upload"
	ClippingSourceYouTube     ClippingSourceKind = "youtube_original_file"
	ClippingSourceGoogleDrive ClippingSourceKind = "google_drive_public"
	ClippingSourceDropbox     ClippingSourceKind = "dropbox_public"
)

type ClippingSourceStatus string

const (
	ClippingSourceUploading ClippingSourceStatus = "uploading"
	ClippingSourceImporting ClippingSourceStatus = "importing"
	ClippingSourceReady     ClippingSourceStatus = "ready"
	ClippingSourceFailed    ClippingSourceStatus = "failed"
	ClippingSourceDeleted   ClippingSourceStatus = "deleted"
)

type ClippingJobStatus string

const (
	ClippingJobQueued       ClippingJobStatus = "queued"
	ClippingJobRunning      ClippingJobStatus = "running"
	ClippingJobPausedBudget ClippingJobStatus = "paused_budget"
	ClippingJobCompleted    ClippingJobStatus = "completed"
	ClippingJobFailed       ClippingJobStatus = "failed"
	ClippingJobCanceled     ClippingJobStatus = "canceled"
)

type ClippingStageStatus string

const (
	ClippingStageQueued       ClippingStageStatus = "queued"
	ClippingStageRunning      ClippingStageStatus = "running"
	ClippingStagePausedBudget ClippingStageStatus = "paused_budget"
	ClippingStageUncertain    ClippingStageStatus = "uncertain"
	ClippingStageCompleted    ClippingStageStatus = "completed"
	ClippingStageFailed       ClippingStageStatus = "failed"
	ClippingStageCanceled     ClippingStageStatus = "canceled"
)

// ClippingSourceCreate contains metadata supplied by an authenticated source
// adapter. Storage paths and IDs are always generated by Store.
type ClippingSourceCreate struct {
	Kind              ClippingSourceKind
	OriginalName      string
	MediaType         string
	DeclaredSizeBytes int64
	SourceURL         string
	RightsAttested    bool
	RetainUntil       int64
}

// ClippingSource is the durable source record. SourceURL and StoragePath may
// contain sensitive data or host-local paths and must never be serialized.
type ClippingSource struct {
	ID                string               `json:"id"`
	Kind              ClippingSourceKind   `json:"kind"`
	Status            ClippingSourceStatus `json:"status"`
	OriginalName      string               `json:"original_name,omitempty"`
	MediaType         string               `json:"media_type,omitempty"`
	SourceURL         string               `json:"-"`
	StoragePath       string               `json:"-"`
	RightsAttested    bool                 `json:"rights_attested"`
	Failure           string               `json:"error,omitempty"`
	DeclaredSizeBytes int64                `json:"declared_size_bytes,omitempty"`
	ReservedSizeBytes int64                `json:"reserved_size_bytes,omitempty"`
	SizeBytes         int64                `json:"size_bytes,omitempty"`
	UploadOffset      int64                `json:"upload_offset,omitempty"`
	DurationMS        int64                `json:"duration_ms,omitempty"`
	SHA256            string               `json:"sha256,omitempty"`
	RetainUntil       int64                `json:"retain_until,omitempty"`
	ImportAttempts    int                  `json:"import_attempts,omitempty"`
	NextImportAt      int64                `json:"next_import_at,omitempty"`
	ImportLeaseUntil  int64                `json:"-"`
	MediaLeaseUntil   int64                `json:"-"`
	CleanupComplete   bool                 `json:"cleanup_complete"`
	CreatedAt         int64                `json:"created_at"`
	UpdatedAt         int64                `json:"updated_at"`
	DeletedAt         int64                `json:"deleted_at,omitempty"`
}

type ClippingBatchCreate struct {
	IdempotencyKey      string
	BudgetLimitMicroUSD int64
	Jobs                []ClippingJobCreate
}

type ClippingJobCreate struct {
	SourceID            string
	BudgetLimitMicroUSD int64
}

type ClippingBatch struct {
	ID                  string            `json:"id"`
	IdempotencyKey      string            `json:"-"`
	Status              ClippingJobStatus `json:"status"`
	BudgetLimitMicroUSD int64             `json:"budget_limit_micro_usd"`
	ReservedMicroUSD    int64             `json:"reserved_micro_usd"`
	SpentMicroUSD       int64             `json:"spent_micro_usd"`
	CreatedAt           int64             `json:"created_at"`
	UpdatedAt           int64             `json:"updated_at"`
}

type ClippingJob struct {
	ID                  string            `json:"id"`
	BatchID             string            `json:"batch_id"`
	SourceID            string            `json:"source_id"`
	Status              ClippingJobStatus `json:"status"`
	BudgetLimitMicroUSD int64             `json:"budget_limit_micro_usd"`
	ReservedMicroUSD    int64             `json:"reserved_micro_usd"`
	SpentMicroUSD       int64             `json:"spent_micro_usd"`
	Error               string            `json:"error,omitempty"`
	CreatedAt           int64             `json:"created_at"`
	UpdatedAt           int64             `json:"updated_at"`
}

type ClippingStage struct {
	JobID            string              `json:"job_id"`
	Name             string              `json:"name"`
	Status           ClippingStageStatus `json:"status"`
	IdempotencyKey   string              `json:"idempotency_key"`
	AttemptID        string              `json:"attempt_id,omitempty"`
	Attempt          int                 `json:"attempt"`
	LeaseExpiresAt   int64               `json:"lease_expires_at,omitempty"`
	ReservedMicroUSD int64               `json:"reserved_micro_usd"`
	ActualMicroUSD   int64               `json:"actual_micro_usd"`
	LeaseToken       string              `json:"-"`
	Error            string              `json:"error,omitempty"`
	CreatedAt        int64               `json:"created_at"`
	UpdatedAt        int64               `json:"updated_at"`
}

// ClippingArtifact stores canonical source-time references in integer
// milliseconds. PayloadJSON is versioned application data; TimeRanges are
// validated against the source duration before persistence.
type ClippingArtifact struct {
	JobID            string              `json:"job_id"`
	Type             string              `json:"type"`
	SchemaVersion    string              `json:"schema_version"`
	Version          int                 `json:"version"`
	SourceDurationMS int64               `json:"source_duration_ms"`
	TimeRanges       []ClippingTimeRange `json:"time_ranges"`
	PayloadJSON      string              `json:"payload_json"`
	CreatedAt        int64               `json:"created_at"`
}

type ClippingTimeRange struct {
	StartMS int64 `json:"start_ms"`
	EndMS   int64 `json:"end_ms"`
}

func validClippingSourceKind(kind ClippingSourceKind) bool {
	switch kind {
	case ClippingSourceUpload, ClippingSourceYouTube, ClippingSourceGoogleDrive, ClippingSourceDropbox:
		return true
	default:
		return false
	}
}

func clippingSourceInitialStatus(kind ClippingSourceKind) ClippingSourceStatus {
	if kind == ClippingSourceUpload {
		return ClippingSourceUploading
	}
	return ClippingSourceImporting
}

func clippingLeaseExpiry(now time.Time, leaseFor time.Duration) int64 {
	if leaseFor <= 0 {
		leaseFor = time.Minute
	}
	return now.Add(leaseFor).Unix()
}
